#!/bin/sh

SRCROOT=`pwd`
export SRCROOT

if [ ! -d tarball ]; then
	mkdir -p tarball
fi
if [ ! -d dist ]; then
	mkdir -p dist
fi
if [ ! -d initrd ]; then
	doas mkdir -p initrd/proc
	doas mkdir -p initrd/sys
	doas mkdir -p initrd/tmp
	doas mkdir -p initrd/dev
	doas mkdir -p initrd/newroot
	doas mkdir -p initrd/bin
	doas mkdir -p initrd/lib
fi
if [ ! -d root ]; then
	doas mkdir -p root/usr/include/sys
	doas mkdir -p root/usr/share
	doas mkdir -p root/usr/man
	doas mkdir -p root/lib64
	doas mkdir -p root/bin
	doas mkdir -p root/tmp
	doas mkdir -p root/run
	doas mkdir -p root/var/run
	doas mkdir -p root/var/log
	doas mkdir -p root/var/db
	doas mkdir -p root/root
	doas mkdir -p root/var/mail
	doas mkdir -p root/var/spool/mqueue
	doas mkdir -p root/isolinux
	doas mkdir -p root/etc

	doas install -d -m755 root/etc/mail

	doas mkdir -p root/proc
	doas mkdir -p root/sys
	doas mkdir -p root/dev

	doas ln -s ../proc/mounts root/etc/mtab

	doas ln -s ../tmp/resolv.conf root/etc/resolv.conf
	doas ln -s ../man root/usr/share/man

	doas ln -s ./ksh root/bin/sh
	doas ln -s ./sbin root/usr/bin
	doas ln -s ../bin root/usr/sbin
	doas ln -s ./bin root/sbin
	
	doas ln -s ../usr/linux/sbin/agetty root/sbin/getty
	
	doas ln -s ../tmp root/var/tmp

	doas ln -s ./lib root/usr/lib64
	doas ln -s ../lib root/usr/lib
	doas ln -s ./lib64 root/lib
fi
download () {
	name=`echo "$1" | rev | cut -d"/" -f1 | rev`
	topdir="$2"
	if [ -f tarball/$name ]; then
		echo " - not required to download $1"
	else
		echo " - getting $1"
		wget -O tarball/$name $1
	fi
	if [ -d dist/$2 ]; then
		echo " - not required to extract tarball/$name"
	else
		echo " - extracting tarball/$name"
		tar xvf tarball/$name -C dist
	fi
}

OLD=""
NEW=""

enter () {
	OLD=`pwd`
	NEW=$1
	echo " - entering $1"
	cd $1
}

leave () {
	echo " - leaving $NEW"
	cd $OLD
}

set_cc () {
	CC=$SRCROOT/dist/x86_64-linux-musl-cross/bin/x86_64-linux-musl-gcc
	CXX=$SRCROOT/dist/x86_64-linux-musl-cross/bin/x86_64-linux-musl-g++
	AS=$SRCROOT/dist/x86_64-linux-musl-cross/bin/x86_64-linux-musl-as
	LD=$SRCROOT/dist/x86_64-linux-musl-cross/bin/x86_64-linux-musl-ld
	export CC
	export CXX
	export AS
	export LD
	CFLAGS="--sysroot=$SRCROOT/root -O2 -Wl,--sysroot=$SRCROOT/root"
	CXXFLAGS="--sysroot=$SRCROOT/root -O2"
	LDFLAGS="--sysroot=$SRCROOT/root -O2"
	export CFLAGS
	export CXXFLAGS
	export LDFLAGS
}

build () {
	enter $1
	if [ -f .bootstrapped ]; then
		if [ -f ".bootstrapped" ]; then
			echo " - not bootstrapping"
		else
			echo " - bootstrapping"
			./bootstrap.sh || exit 1
			touch .bootstrapped
		fi
	fi
	if [ -f configure -o $1 = dist/net-tools-2.10 ]; then
		if [ -f ".configured" ]; then
			echo " - not configuring"
		else
			echo " - configuring"
			case "$1" in
				dist/zlib-*)
					./configure --prefix=/usr $4 || exit 1
					;;
				dist/util-linux-*)
					./configure --prefix=/usr/linux --sysconfdir=/etc --mandir=/usr/man $4 || exit 1
					;;
				dist/net-tools-*)
					yes | make config
					sed -Ei 's/#define (HAVE_AFECONET|HAVE_HWSTRIP|HAVE_HWTR|HAVE_SELINUX|HAVE_AFBLUETOOTH|HAVE_AFDECnet) 1//g' config.h
					sed -Ei 's/(HAVE_AFECONET|HAVE_HWSTRIP|HAVE_HWTR|HAVE_SELINUX|HAVE_AFBLUETOOTH|HAVE_AFDECnet)=1/\1=0/g' config.make
					;;
				*)
					./configure --prefix=/usr --sysconfdir=/etc --mandir=/usr/man $4 || exit 1
					;;
			esac
			touch .configured
		fi
	fi
	if [ -f ".built" ]; then
		echo " - not building"
	else
		echo " - building"
		make -j $(nproc) || exit 1
		touch .built
	fi
	if [ -f ".installed" ]; then
		echo " - not installing"
	else
		echo " - installing"
		doas make install -j $(nproc) $2=$SRCROOT/root $3 || exit 1
		touch .installed
	fi
	leave
}
SLACKWARE_ROOT="http://mirror.slackware.jp/slackware"
LINUX_VER=`wget -O - "$SLACKWARE_ROOT/slackware64-current/kernels/VERSIONS.TXT" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+'`
echo " - Linux $LINUX_VER"

if [ ! -f root/usr/include/sys/cdefs.h ]; then
	doas wget https://github.com/openembedded/openembedded-core/raw/refs/heads/master/meta/recipes-core/musl/bsd-headers/sys-cdefs.h -O root/usr/include/sys/cdefs.h
fi

if [ ! -f root/usr/include/sys/queue.h ]; then
	doas wget https://github.com/openembedded/openembedded-core/raw/refs/heads/master/meta/recipes-core/musl/bsd-headers/sys-queue.h -O root/usr/include/sys/queue.h
fi

if [ ! -f root/usr/include/sys/tree.h ]; then
	doas wget https://github.com/openembedded/openembedded-core/raw/refs/heads/master/meta/recipes-core/musl/bsd-headers/sys-tree.h -O root/usr/include/sys/tree.h
fi

download $SLACKWARE_ROOT/slackware64-current/source/k/linux-$LINUX_VER.tar.xz linux-$LINUX_VER
if [ ! -d root/usr/include/linux ]; then
	enter dist/linux-$LINUX_VER
	doas make headers_install ARCH=x86_64 INSTALL_HDR_PATH=$SRCROOT/root/usr
	leave
fi
if [ ! -f root/bzImage ]; then
	doas wget $SLACKWARE_ROOT/slackware64-current/kernels/generic.s/bzImage -O root/bzImage
fi

if [ ! -f tarball/kernel-$LINUX_VER.txz ]; then
	wget $SLACKWARE_ROOT/slackware64-current/slackware64/a/kernel-generic-$LINUX_VER-x86_64-1.txz -O tarball/kernel-$LINUX_VER.txz
fi
if [ ! -d root/lib/modules ]; then
	doas tar xkvf tarball/kernel-$LINUX_VER.txz -C root/usr lib
fi

download http://musl.cc/x86_64-linux-musl-cross.tgz x86_64-linux-musl-cross
download http://git.musl-libc.org/cgit/musl/snapshot/musl-1.2.5.tar.gz musl-1.2.5
download http://invisible-island.net/archives/ncurses/ncurses-6.5.tar.gz ncurses-6.5
download https://mandoc.bsd.lv/snapshots/mandoc-1.14.6.tar.gz mandoc-1.14.6
download http://www.zlib.net/zlib-1.3.1.tar.gz zlib-1.3.1
download https://ftp.gnu.org/gnu/less/less-668.tar.gz less-668
download https://www.kernel.org/pub/linux/utils/util-linux/v2.40/util-linux-2.40.tar.gz util-linux-2.40
download https://github.com/sqlite/sqlite/archive/refs/tags/version-3.47.0.tar.gz sqlite-version-3.47.0
download https://mirrors.edge.kernel.org/pub/linux/utils/kernel/kmod/kmod-33.tar.gz kmod-33
download https://downloads.sourceforge.net/project/net-tools/net-tools-2.10.tar.xz net-tools-2.10
download https://github.com/shadow-maint/shadow/releases/download/4.16.0/shadow-4.16.0.tar.xz shadow-4.16.0
download https://ftp.sendmail.org/sendmail.8.18.1.tar.gz sendmail-8.18.1

set_cc

cp source/sbrk.c dist/musl-1.2.5/src/linux/
build dist/musl-1.2.5 DESTDIR
build musl-fts DESTDIR

build dist/zlib-1.3.1 DESTDIR "" "--enable-shared"
build dist/shadow-4.16.0 DESTDIR "" "--without-libbsd --with-bcrypt --with-yescrypt"

echo "PREFIX=/usr" > dist/mandoc-1.14.6/configure.local
echo "CC=$CC" >> dist/mandoc-1.14.6/configure.local
echo "LD=$LD" >> dist/mandoc-1.14.6/configure.local
echo "CFLAGS=\"$CFLAGS\"" >> dist/mandoc-1.14.6/configure.local
echo "LDFLAGS=\"$LDFLAGS\"" >> dist/mandoc-1.14.6/configure.local
build dist/mandoc-1.14.6 DESTDIR

LD_LIBRARY_PATH=$SRCROOT/root/usr/lib
export LD_LIBRARY_PATH
build dist/ncurses-6.5 DESTDIR "" "--with-shared --with-termlib --enable-symlinks --disable-widec"
unset LD_LIBRARY_PATH

cp config/heritage.mk heritage/Config.mk
build heritage DESTDIR

build sysvinit ROOT "mandir=/usr/man"

build pdksh DESTDIR "prefix=$SRCROOT/root/usr"
build vi DESTDIR "MANDIR=/usr/man"

build dist/less-668 DESTDIR

build dist/sqlite-version-3.47.0 DESTDIR "" "--disable-tcl --disable-readline"

build dist/util-linux-2.40 DESTDIR "" "--without-systemd --without-python --without-ncursesw"

build dist/kmod-33 DESTDIR

build dist/net-tools-2.10 DESTDIR

doas groupadd -g 80 smmsp
doas useradd -u 80 -s /bin/false -d /dev/null -g smmsp -c "Sendmail Daemon" smmsp

cat > dist/sendmail-8.18.1/devtools/Site/site.config.m4 << EOF
define(\`confCC',\`$CC --sysroot=$SRCROOT/root')
define(\`confOPTIMIZE',\`-O2')
APPENDDEF(\`confENVDEF',\`-UNIS -DHASRRESVPORT=0 -DHASSTRERROR')
EOF

build dist/sendmail-8.18.1 DESTDIR

enter dist/sendmail-8.18.1
cd cf/cf
cp generic-linux.mc sendmail.mc
sh Build sendmail.cf
cd ../..
doas install -m644 cf/cf/submit.mc $SRCROOT/root/etc/mail
doas install -m644 cf/cf/sendmail.mc $SRCROOT/root/etc/mail
doas cp -R cf/cf/* $SRCROOT/root/etc/mail/
leave

doas groupdel smmsp
doas userdel smmsp

if [ ! -f root/sbin/popdev ]; then
	echo " - compiling popdev"
	doas $CC $CFLAGS $LDFLAGS -o root/sbin/popdev source/popdev.c
else
	echo " - not compiling popdev"
fi

if [ ! -f root/sbin/irinit ]; then
	echo " - compiling irinit"
	doas $CC $CFLAGS $LDFLAGS -I$SRCROOT/root/usr/linux/include -L$SRCROOT/root/usr/linux/lib -o root/sbin/irinit source/irinit.c $SRCROOT/root/usr/linux/lib/libblkid.a
else
	echo " - not compiling irinit"
fi

echo " - copying files"
for i in `ls -d base/*`; do
	TO=`grep "TO: " $i | sed "s/# TO: //g"`
	echo " - $i -> $TO"
	doas cp $i $SRCROOT/root/$TO
done

doas chroot root makewhatis /usr/man

echo " - constructing initrd.gz"
if [ ! -f root/initrd.gz ]; then
	doas cp root/bin/sh initrd/bin/sh
	doas cp root/bin/echo initrd/bin/echo
	doas cp root/bin/find initrd/bin/find
	doas cp root/bin/cat initrd/bin/cat
	doas cp root/bin/modprobe initrd/bin/modprobe
	doas cp root/sbin/irinit initrd/init
	doas cp root/sbin/popdev initrd/popdev
	doas cp root/lib/libc.so initrd/lib/libc.so
	doas cp root/lib/libc.so initrd/lib/ld-musl-x86_64.so.1
	doas cp root/lib/libfts.so initrd/lib/libfts.so
	doas cp root/lib/libfts.so initrd/lib/libfts.so.0
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/drivers/usb
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/drivers/scsi
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/fs
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/lib
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/arch
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/crypto
	doas mkdir -p initrd/lib/modules/$LINUX_VER/kernel/block
	doas cp -rf root/lib/modules/$LINUX_VER/modules.* initrd/lib/modules/$LINUX_VER/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/drivers/scsi/* initrd/lib/modules/$LINUX_VER/kernel/drivers/scsi/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/drivers/usb/* initrd/lib/modules/$LINUX_VER/kernel/drivers/usb/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/fs/* initrd/lib/modules/$LINUX_VER/kernel/fs/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/lib/* initrd/lib/modules/$LINUX_VER/kernel/lib/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/arch/* initrd/lib/modules/$LINUX_VER/kernel/arch/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/block/* initrd/lib/modules/$LINUX_VER/kernel/block/
	doas cp -rf root/lib/modules/$LINUX_VER/kernel/crypto/* initrd/lib/modules/$LINUX_VER/kernel/crypto/
	cd initrd
	find . | cpio -o -H newc > ../init.rd
	cd ..
	gzip -c init.rd > initrd.gz
	doas mv initrd.gz root/initrd.gz
	rm -f init.rd
fi

doas cp /usr/lib/ISOLINUX/isolinux.bin root/isolinux/
doas cp /usr/lib/syslinux/modules/bios/ldlinux.c32 root/isolinux/
doas cp /usr/lib/syslinux/modules/bios/libutil.c32 root/isolinux/
doas cp /usr/lib/syslinux/modules/bios/menu.c32 root/isolinux/

doas sh -c 'cat > root/isolinux/isolinux.cfg' << EOF
default menu.c32
timeout 50
menu title Boot Menu
menu rows 1
label linux
       kernel /bzImage
       initrd /initrd.gz
       append root=LABEL=BLNXINST rootfstype=iso9660 loglevel=4 installer
EOF

doas sh -c 'echo berkeley > root/etc/nodename'

doas sh -c 'cat > root/etc/issue' << EOF
Welcome to Berkeley Linux - The Linux Distribution
           from Nishi
System name: \n
EOF

doas chroot root /usr/sbin/groupadd -g 0 root
doas chroot root /usr/sbin/groupadd -g 1 daemon
doas chroot root /usr/sbin/groupadd -g 2 bin
doas chroot root /usr/sbin/groupadd -g 80 smmsp
doas chroot root /usr/sbin/useradd -p x -g 0 -u 0 -d /root -s /bin/sh root
doas chroot root /usr/sbin/useradd -u 80 -s /bin/false -d /dev/null -g smmsp -c "Sendmail Daemon" smmsp
echo "root:`mkpasswd -m sha512crypt root`:0::::::" | doas sh -c 'cat > root/etc/shadow'
echo root:root | doas chroot root /usr/sbin/chpasswd -c SHA512

doas chmod 644 root/etc/passwd
doas chmod 644 root/etc/group
doas chmod 600 root/etc/shadow
doas chmod 4755 root/usr/sbin/unix_chkpwd
doas chmod 1777 root/var/mail
doas install -m700 -d root/var/spool/mqueue

doas xorriso -as mkisofs -V "BLNXINST" -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin -b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4 -o output.iso root
