#!/bin/sh
doas rm -rf dist tarball root initrd
for i in heritage musl-fts sysvinit pdksh vi; do
	cd $i
	make distclean
	rm -f .installed
	rm -f .built
	rm -f .bootstrapped
	rm -f .configured
	cd ..
done
